source "https://rubygems.org"

ruby "3.0.2"

gem "rails", "~> 7.1.6"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
  gem "rspec-rails", "~> 6.1"
  gem "webmock", "~> 3.23"
end

group :development do
  gem "dotenv-rails", "~> 3.1"
  gem "rubocop", "~> 1.50", require: false # enforces the HouseAccount STYLE.md limits
end
